
const Main = () => {
    return (
        <div className="container mt-16 p-8">
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
            <p className="text-justify text-lg mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab blanditiis commodi dolorem dolores ipsam necessitatibus obcaecati perferendis repellat tenetur vel? Accusantium corporis ea eius fugit minima nisi nobis soluta suscipit ullam velit. Aliquam consectetur, culpa dignissimos ea ex explicabo illo itaque, laborum nulla perferendis porro, quod totam voluptatem. Adipisci amet aspernatur, deleniti laborum neque omnis quisquam sequi tempora. Aliquam at, consequatur eum incidunt itaque nulla tempore veniam. Aut blanditiis commodi debitis error excepturi, expedita explicabo facere fuga inventore magnam nemo obcaecati pariatur perspiciatis provident qui quis quo, quod rem rerum saepe sapiente sequi sint soluta suscipit ut, velit veniam vitae.</p>
        </div>
    );
};

export default Main;
